import type { Story } from "../../models/types";
import { t } from "../topics/helpers";

/**
 * A story is just a couple of narration beats wrapped around one real
 * activity generated by the same engine every other activity uses (see
 * activityTopicId/activityType, resolved through generateActivity()) - so
 * "find the red balloon" becomes "help Bunny find his red balloon" instead
 * of a bare quiz question.
 */
export const stories: Story[] = [
  {
    id: "bunny-red-balloon",
    worldId: "rainbow-garden",
    title: t("הבלון האדום של ארנבון", "Bunny's Red Balloon"),
    icon: "🎈",
    scenes: [
      {
        id: "s1",
        kind: "narration",
        mascotMood: "idle",
        line: t("ארנבון מחפש את הבלון האדום שלו בגן.", "Bunny is looking for his red balloon in the garden."),
        emoji: "🌸",
      },
      {
        id: "s2",
        kind: "narration",
        mascotMood: "thinking",
        line: t("איפה הוא יכול להיות? בואו נעזור לו!", "Where could it be? Let's help him look!"),
        emoji: "🌈",
      },
      {
        id: "s3",
        kind: "activity",
        activityTopicId: "colors",
        activityType: "FIND",
        forcedVocabId: "red",
      },
      {
        id: "s4",
        kind: "narration",
        mascotMood: "celebrating",
        line: t("יאיי! מצאתם את הבלון של ארנבון!", "Yaaay! You found Bunny's balloon!"),
        emoji: "🎈",
      },
    ],
  },
  {
    id: "bunny-farm-visit",
    worldId: "animal-forest",
    title: t("ארנבון מבקר בחווה", "Bunny Visits the Farm"),
    icon: "🐮",
    scenes: [
      {
        id: "s1",
        kind: "narration",
        mascotMood: "idle",
        line: t("ארנבון הגיע לחווה ופתאום שמע קול מוזר...", "Bunny arrived at the farm and suddenly heard a funny sound..."),
        emoji: "🌳",
      },
      {
        id: "s2",
        kind: "narration",
        mascotMood: "thinking",
        line: t("מוווו! מי אומר את זה?", "Mooo! Who says that?"),
        emoji: "❓",
      },
      {
        id: "s3",
        kind: "activity",
        activityTopicId: "animals",
        activityType: "FIND",
        forcedVocabId: "cow",
      },
      {
        id: "s4",
        kind: "narration",
        mascotMood: "celebrating",
        line: t("נכון! זו הפרה. כל הכבוד!", "That's right! It's the cow. Great job!"),
        emoji: "🐮",
      },
    ],
  },
];

export function getStory(id: string): Story | undefined {
  return stories.find((story) => story.id === id);
}

export function storiesForWorld(worldId: string): Story[] {
  return stories.filter((story) => story.worldId === worldId);
}
